#include "WebUIEditor.h"
#include "WebUIContent.h"   // generated by Tools/embed_html.py

using P = ReverbPluginProcessor;

namespace
{

/** Dark UI background — prevents a white flash while WebView2 initialises. */
const juce::Colour kWebViewBackground { 0xff080b12 };

/**
 * WebView2-only browser options for Windows DAW hosts (e.g. Studio One).
 *
 * A writable user-data folder is mandatory inside plugin sandboxes; without it
 * WebView2 fails to start and JUCE silently falls back to legacy IE/MSHTML.
 */
juce::WebBrowserComponent::Options makeWebBrowserOptions()
{
    auto userDataFolder =
        juce::File::getSpecialLocation (juce::File::tempDirectory)
            .getChildFile ("TiaVerb_WebView2_Data");

    userDataFolder.createDirectory();

    return juce::WebBrowserComponent::Options{}
        .withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
        .withWinWebView2Options (
            juce::WebBrowserComponent::Options::WinWebView2{}
                .withUserDataFolder (userDataFolder)
                .withBackgroundColour (kWebViewBackground))
        .withKeepPageLoadedWhenBrowserIsHidden();
}

} // namespace

// ── Parameter ID list (must match APVTS) ─────────────────────────────────────
static const char* const kAllParamIds[] =
{
    P::kParamTime, P::kParamSize, P::kParamDamping,
    P::kParamPreDelay, P::kParamMix,
};

// ── Browser (WebView2-only) ───────────────────────────────────────────────────
WebUIEditor::Browser::Browser (WebUIEditor& owner)
    : juce::WebBrowserComponent ([]
    {
        const auto options = makeWebBrowserOptions();

       #if JUCE_WINDOWS
        // Refuse to proceed silently into the IE fallback path in debug builds.
        jassert (juce::WebBrowserComponent::areOptionsSupported (options));
       #endif

        return options;
    }()),
      owner_(owner)
{
}

// ── Constructor / Destructor ──────────────────────────────────────────────────
WebUIEditor::WebUIEditor(ReverbPluginProcessor& proc)
    : AudioProcessorEditor(proc),
      processor_(proc),
      presetManager_(proc.apvts),
      browser_(*this)
{
    addAndMakeVisible(browser_);
    setSize(720, 480);

    // Prime the shadow map so the first timerCallback pushes everything
    for (const char* id : kAllParamIds)
        lastPushed_[id] = -1e9f;

    loadUI();

    // Push initial param state to JS 3× per second while page is loading,
    // then upgrade to 60 fps once pageFinishedLoading fires.
    startTimerHz(3);
}

WebUIEditor::~WebUIEditor()
{
    stopTimer();
    // Clean up the temp file
    if (tempHtmlFile_.existsAsFile())
        tempHtmlFile_.deleteFile();
}

// ── resized ───────────────────────────────────────────────────────────────────
void WebUIEditor::resized()
{
    browser_.setBounds(getLocalBounds());
}

// ── loadUI ────────────────────────────────────────────────────────────────────
void WebUIEditor::loadUI()
{
    tempHtmlFile_ = juce::File::getSpecialLocation(juce::File::tempDirectory)
                    .getChildFile("tiaverb_ui.html");

    // Write explicit UTF-8 with BOM so WebView2 on Windows never mis-detects
    // encoding (prevents mojibake like "â??" for multiplication / arrows).
    const juce::String html = juce::String::fromUTF8(kWebUIHTML);
    juce::MemoryOutputStream mos;
    static constexpr char kUtf8Bom[] = { '\xEF', '\xBB', '\xBF' };
    mos.write(kUtf8Bom, sizeof(kUtf8Bom));
    mos.write(html.toRawUTF8(), (size_t) html.getNumBytesAsUTF8());
    tempHtmlFile_.replaceWithData(mos.getData(), mos.getDataSize());

    const auto fileUrl = juce::URL(tempHtmlFile_).toString(false);
    browser_.goToURL(fileUrl);
}

// ── handleJuceURL — called from Browser::pageAboutToLoad ─────────────────────
void WebUIEditor::handleJuceURL(const juce::String& url)
{
    // Strip scheme:  "juce://action?k=v&k=v"  →  action, params
    const auto withoutScheme = url.substring(7); // drop "juce://"
    const int  qPos          = withoutScheme.indexOf("?");
    const auto action        = qPos >= 0 ? withoutScheme.substring(0, qPos) : withoutScheme;
    const auto queryStr      = qPos >= 0 ? withoutScheme.substring(qPos + 1) : juce::String{};

    auto params = parseQuery(url);

    if (action == "setParam")
    {
        const auto id    = params["id"];
        const float val  = params["value"].getFloatValue();

        if (auto* param = dynamic_cast<juce::RangedAudioParameter*>(
                processor_.apvts.getParameter(id)))
        {
            const float normalized = param->convertTo0to1(val);
            param->setValueNotifyingHost(normalized);

            // Update shadow so the timer doesn't echo it back immediately
            lastPushed_[id] = val;
        }
    }
    else if (action == "loadPreset")
    {
        if (params.count("name") > 0)
            presetManager_.loadPresetByName(params["name"]);
        else
            presetManager_.loadPreset(params["idx"].getIntValue());

        pushAllParamsToJS();
    }
    // "advancedView" — no-op on the C++ side; the JS handles the layout itself.
}

// ── pushParamToJS ─────────────────────────────────────────────────────────────
void WebUIEditor::pushParamToJS(const juce::String& paramId, float value)
{
    if (!pageReady_) return;

    const juce::String script =
        "window._juceUpdate('" + paramId + "'," + juce::String(value, 6) + ")";
    browser_.evaluateJavascript(script);
}

void WebUIEditor::pushAllParamsToJS()
{
    if (!pageReady_) return;

    juce::String json = "{";
    bool first = true;

    for (const char* id : kAllParamIds)
    {
        if (auto* raw = processor_.apvts.getRawParameterValue(id))
        {
            const float current = raw->load();
            lastPushed_[id] = current;

            if (! first) json += ",";
            first = false;
            json += "\"" + juce::String(id) + "\":" + juce::String(current, 6);
        }
    }
    json += "}";

    browser_.evaluateJavascript("window._juceBatchUpdate(" + json + ")");
}

// ── Timer: sync APVTS → JS ────────────────────────────────────────────────────
void WebUIEditor::timerCallback()
{
    if (!pageReady_) return;

    for (const char* id : kAllParamIds)
    {
        if (auto* raw = processor_.apvts.getRawParameterValue(id))
        {
            const float current = raw->load();
            auto&       last    = lastPushed_[id];
            if (std::abs(current - last) > 1e-6f)
            {
                last = current;
                pushParamToJS(id, current);
            }
        }
    }
}

// ── Browser ───────────────────────────────────────────────────────────────────
bool WebUIEditor::Browser::pageAboutToLoad(const juce::String& newURL)
{
    if (newURL.startsWith("juce://"))
    {
        // Run on message thread — safe to call APVTS here
        owner_.handleJuceURL(newURL);
        return false; // cancel navigation; keeps current page intact
    }
    return true;
}

void WebUIEditor::Browser::pageFinishedLoading(const juce::String& /*url*/)
{
    owner_.pageReady_ = true;
    owner_.pushAllParamsToJS();
    owner_.startTimerHz(60);
}

// ── parseQuery ────────────────────────────────────────────────────────────────
std::map<juce::String,juce::String> WebUIEditor::parseQuery(const juce::String& url)
{
    std::map<juce::String,juce::String> out;

    const int qPos = url.indexOf("?");
    if (qPos < 0) return out;

    const auto query = url.substring(qPos + 1);
    for (const auto& pair : juce::StringArray::fromTokens(query, "&", ""))
    {
        const int eqPos = pair.indexOf("=");
        if (eqPos > 0)
        {
            const auto key = juce::URL::removeEscapeChars(pair.substring(0, eqPos));
            const auto val = juce::URL::removeEscapeChars(pair.substring(eqPos + 1));
            out[key] = val;
        }
    }
    return out;
}
