#!/usr/bin/env python3
"""
embed_html.py  —  converts WebUI/plugin_ui.html into Plugin/WebUIContent.h

Usage:
  python Tools/embed_html.py

The generated header exposes a single C-string constant:
  extern const char* kWebUIHTML;

Run this whenever plugin_ui.html is modified.  The header is committed to
source control so the plugin builds without Node.js.
"""
import pathlib, sys, re

ROOT    = pathlib.Path(__file__).resolve().parent.parent
SRC     = ROOT / "WebUI" / "plugin_ui.html"
DEST    = ROOT / "Plugin" / "WebUIContent.h"
DELIM   = "WEBUICONTENT_RAW"   # raw-string delimiter — must not appear in HTML

def main():
    if not SRC.exists():
        print(f"ERROR: {SRC} not found.", file=sys.stderr)
        sys.exit(1)

    html = SRC.read_text(encoding="utf-8")

    # Warn if raw non-ASCII appears in HTML (use STR.\u escapes in JS instead)
    non_ascii = [ch for ch in html if ord(ch) > 127]
    if non_ascii:
        unique = sorted(set(non_ascii))
        print(f"WARN: {len(non_ascii)} non-ASCII chars in HTML "
              f"({''.join(unique[:12])}{'...' if len(unique)>12 else ''}). "
              "Prefer ASCII + JS \\u escapes to avoid mojibake.", file=sys.stderr)

    # Safety: make sure the chosen delimiter isn't inside the HTML
    if DELIM in html:
        print(f"ERROR: delimiter '{DELIM}' appears inside the HTML. "
              "Choose a different DELIM in this script.", file=sys.stderr)
        sys.exit(1)

    guard = "PLUGIN_WEBUICONTENT_H"
    header = f"""\
// ──────────────────────────────────────────────────────────────────────────────
// WebUIContent.h  —  AUTO-GENERATED by Tools/embed_html.py
//                    DO NOT EDIT BY HAND.  Re-run the script after editing
//                    WebUI/plugin_ui.html.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

// The full HTML/CSS/JS of the plugin UI, embedded as a C++ raw string literal.
// Loaded by WebUIEditor into a juce::WebBrowserComponent via a temp file.
static const char kWebUIHTML[] = R"{DELIM}(
{html}
){DELIM}";
"""
    DEST.write_text(header, encoding="utf-8", newline="\n")
    print(f"OK  Wrote {DEST}  ({len(html):,} bytes of HTML, {len(header):,} total)")

if __name__ == "__main__":
    main()
