#!/usr/bin/env python3
"""
embed_html.py  —  converts WebUI/plugin_ui.html into Plugin/WebUIContent.h

Usage:
  python Tools/embed_html.py

The generated header exposes a single C-string constant:
  extern const char* kWebUIHTML;

Run this whenever plugin_ui.html is modified.  The header is committed to
source control so the plugin builds without Node.js.

Local font files under WebUI/fonts/ are inlined as base64 data URIs so the
UI works offline inside WebView2 (HTML is written to a single temp file).
"""
import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "WebUI" / "plugin_ui.html"
FONTS_DIR = ROOT / "WebUI" / "fonts"
DEST = ROOT / "Plugin" / "WebUIContent.h"
DELIM = "WEBUICONTENT_RAW"  # raw-string delimiter — must not appear in HTML

FONT_URL_RE = re.compile(
    r"url\(['\"]fonts/(Inter-\d+)\.woff2['\"]\)"
)


def inline_local_fonts(html: str) -> str:
    """Replace url('fonts/Inter-NNN.woff2') with embedded data URIs."""

    def replace(match: re.Match) -> str:
        stem = match.group(1)
        font_path = FONTS_DIR / f"{stem}.woff2"
        if not font_path.is_file():
            print(f"ERROR: missing font file {font_path}", file=sys.stderr)
            sys.exit(1)
        data = base64.b64encode(font_path.read_bytes()).decode("ascii")
        return f"url(data:font/woff2;base64,{data})"

    return FONT_URL_RE.sub(replace, html)


def main():
    if not SRC.exists():
        print(f"ERROR: {SRC} not found.", file=sys.stderr)
        sys.exit(1)

    html = SRC.read_text(encoding="utf-8")
    html = inline_local_fonts(html)

    # Warn if raw non-ASCII appears in HTML (use STR.\u escapes in JS instead)
    non_ascii = [ch for ch in html if ord(ch) > 127]
    if non_ascii:
        unique = sorted(set(non_ascii))
        print(
            f"WARN: {len(non_ascii)} non-ASCII chars in HTML "
            f"({''.join(unique[:12])}{'...' if len(unique) > 12 else ''}). "
            "Prefer ASCII + JS \\u escapes to avoid mojibake.",
            file=sys.stderr,
        )

    # Safety: make sure the chosen delimiter isn't inside the HTML
    if DELIM in html:
        print(
            f"ERROR: delimiter '{DELIM}' appears inside the HTML. "
            "Choose a different DELIM in this script.",
            file=sys.stderr,
        )
        sys.exit(1)

    guard = "PLUGIN_WEBUICONTENT_H"
    header = f"""\
// ──────────────────────────────────────────────────────────────────────────────
// WebUIContent.h  —  AUTO-GENERATED by Tools/embed_html.py
//                    DO NOT EDIT BY HAND.  Re-run the script after editing
//                    WebUI/plugin_ui.html or WebUI/fonts/.
// ──────────────────────────────────────────────────────────────────────────────
#pragma once

// The full HTML/CSS/JS of the plugin UI, embedded as a C++ raw string literal.
// Loaded by WebUIEditor into a juce::WebBrowserComponent via a temp file.
// Inter fonts are inlined as base64 data URIs — no network required.
static const char kWebUIHTML[] = R"{DELIM}(
{html}
){DELIM}";
"""
    DEST.write_text(header, encoding="utf-8", newline="\n")
    font_count = len(FONT_URL_RE.findall(SRC.read_text(encoding="utf-8")))
    print(
        f"OK  Wrote {DEST}  ({len(html):,} bytes of HTML, {len(header):,} total, "
        f"{font_count} fonts inlined)"
    )


if __name__ == "__main__":
    main()
